# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-21 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='entertainment_pic/%Y/%M/%D/')),
                ('video', models.FileField(blank=True, upload_to='entertainment_video/%Y/%M/%D/')),
                ('youtube_link', models.CharField(blank=True, max_length=255)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entertainment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
