# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-21 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainment',
            name='video',
        ),
        migrations.AddField(
            model_name='entertainment',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
