# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-24 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0002_auto_20180621_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='entertainment_pic_thumbnail/%Y/%M/%D/'),
        ),
    ]
