# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-24 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entertainments', '0004_remove_entertainment_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entertainment',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='entertainment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
