# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-25 10:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainments', '0005_auto_20180624_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='entertainment_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
