# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_customproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproduct',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='instagram_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
