# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-06 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20180906_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='custom_product'),
        ),
    ]
