# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-19 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181113_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='product_size_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_size_fk', to='products.ProductSize'),
        ),
    ]
