# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20181119_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='cart_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
