# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20181122_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_percentage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
