# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(default='/default/default.png', upload_to='profile_pic_tumbnail'),
        ),
    ]
