# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-09 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='profile_pic_thumbnail'),
        ),
    ]
