# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180309_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=models.CharField(choices=[('SHADYGARAGE', 'ShadyGarage'), ('CLASSIC', 'Classic'), ('OFFROAD', 'Offroad'), ('RÅNER', 'Råner'), ('STANCE', 'Stance'), ('TUNER', 'Tuner'), ('MC', 'MC')], default='SHADYGARAGE', max_length=50),
        ),
    ]
