# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180321_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=models.CharField(choices=[('SHADYGARAGE', 'ShadyGarage'), ('CLASSIC', 'Classic'), ('OFFROAD', 'Offroad'), ('STANCE', 'Stance'), ('TUNER', 'Tuner'), ('MC', 'MC')], default='SHADYGARAGE', max_length=50),
        ),
    ]
