# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180109_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='/default/default.png', upload_to='profile_pic'),
        ),
    ]
