# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=models.CharField(choices=[('SHADYGARAGE', 'ShadyGarage'), ('RAAGER', 'Raager'), ('RÅNER', 'Råner')], default='SHADYGARAGE', max_length=50),
        ),
    ]
