# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-18 00:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('addresses', '0001_initial'),
        ('carts', '0002_auto_20180817_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120, unique=True)),
                ('status', models.CharField(choices=[('created', 'Opprettet'), ('paid', 'Betal'), ('packing', 'Pakker'), ('shippped', 'Sendt'), ('finished', 'Finished')], default='created', max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing_profile', to='addresses.Address')),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_billing_profile', to='billing.BillingProfile')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_cart', to='carts.Cart')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_address', to='addresses.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
