# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-23 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180819_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Opprettet'), ('paid', 'Betalt'), ('packing', 'Pakker'), ('shippped', 'Sendt'), ('finished', 'Finished')], default='created', max_length=120),
        ),
    ]
