# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180823_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='money_saved',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
