# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-02 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20180131_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commented', models.BooleanField(default=False)),
                ('liked', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('noti_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notiii', to='posts.PostComment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notification_owner', to=settings.AUTH_USER_MODEL)),
                ('post_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notification_fk', to='posts.Post')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notification_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
