# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_notification_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1020)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment_fk', to='posts.PostComment')),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
