# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='noti_reply_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notiii_reply', to='posts.PostCommentReply'),
        ),
    ]
