# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-08 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_notification_profile_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='profile_pic_url',
        ),
    ]
