# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-05 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20181205_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='has_blurred_thumbnail',
        ),
    ]
