# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-08-19 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='last_4',
            new_name='last4',
        ),
    ]
