# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
