# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_name', models.CharField(max_length=255, unique=True)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField(blank=True, default='19:00:00')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('description', models.TextField()),
                ('meet_image', models.ImageField(blank=True, default='/meets_pic/meet_default.png', upload_to='meets_pic')),
                ('longitude', models.CharField(blank=True, max_length=255)),
                ('latitude', models.CharField(blank=True, max_length=255)),
                ('users_joining', models.ManyToManyField(blank=True, related_name='members_joining_meet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meet_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meet_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_comment', to='meets.Meet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
