# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meet',
            options={'ordering': ['date']},
        ),
    ]
