# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='meet_image',
            field=models.ImageField(blank=True, default='/meets_pic/meet_default.png', upload_to='meets_pic'),
        ),
    ]
