# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0002_meet_meet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='time',
            field=models.TimeField(blank=True, default='19:00:00'),
        ),
    ]
