# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-27 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0003_meet_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='location',
            field=models.CharField(blank=True, max_length=1275),
        ),
    ]
