# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meets', '0003_meet_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='users_joining',
            field=models.ManyToManyField(blank=True, related_name='members_joining_meet', to=settings.AUTH_USER_MODEL),
        ),
    ]
