# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_meet_users_joining'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='meet',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='meet',
            name='meet_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
