# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-27 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_meet_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='longitude',
        ),
    ]
