# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-23 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0006_meet_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet_comments',
            name='meet',
        ),
        migrations.RemoveField(
            model_name='meet_comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Meet_comments',
        ),
    ]
