# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-14 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0007_meet_marker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='marker_image',
            field=models.CharField(choices=[('static/images/e30marker.svg', 'BMW E30'), ('static/images/Stance.svg', 'Audi A4 B8 Stance'), ('static/images/lamborghini.svg', 'Lamborghini Huracan')], default='BMW E30', max_length=255),
        ),
    ]
