# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0009_auto_20180314_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='category',
            field=models.CharField(choices=[('static/images/shady.jpg', 'ShadyGarage'), ('static/images/stance.jpg', 'Stance'), ('static/images/classic.jpg', 'Classic'), ('static/images/tuner.jpg', 'Tuner'), ('static/images/mc.jpg', 'MC'), ('static/images/offroad.jpg', 'Offroad')], default='static/images/burning.jpg', max_length=255),
        ),
    ]
