# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0010_meet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='category',
            field=models.CharField(choices=[('static/images/logomidlertidig.png', 'ShadyGarage'), ('static/images/meet_card/Stance-Car.jpg', 'Stance'), ('static/images/meet_card/Classic-Car.jpg', 'Classic'), ('static/images/meet_card/Tuner-Car.jpg', 'Tuner'), ('static/images/meet_card/Mc.jpg', 'MC'), ('static/images/meet_card/Offroad-Car.jpg', 'Offroad')], default='static/images/burning.jpg', max_length=255),
        ),
    ]
