# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0012_auto_20180526_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='marker_image',
            field=models.CharField(choices=[('static/images/markers/Ford_Mustang_Icon.svg', 'Ford Mustang 69'), ('static/images/markers/Yamaha_R1_Icon.svg', 'Yahmaha R1'), ('static/images/markers/Jeep_Wrangler_Icon.svg', 'Jeep Wrangler'), ('static/images/markers/e30marker.svg', 'BMW E30'), ('static/images/markers/Stance.svg', 'Audi A4 B8 Stance'), ('static/images/markers/lamborghini.svg', 'Lamborghini Huracan')], default='static/images/e30marker.svg', max_length=255),
        ),
    ]
