# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meets', '0014_meet_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetAdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_admin_message', to='meets.Meet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meet_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
