# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-25 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0016_auto_20180611_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='organizer',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
