# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-23 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0017_meet_organizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='category',
        ),
        migrations.AlterField(
            model_name='meet',
            name='meet_image',
            field=models.ImageField(blank=True, default='static/Tuner-Car.jpg', upload_to='meets_pic'),
        ),
    ]
