# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-23 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0018_auto_20190523_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='meet_image',
            field=models.ImageField(upload_to='meets_pic'),
        ),
    ]
