# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-23 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0019_auto_20190523_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='location',
        ),
        migrations.AddField(
            model_name='meet',
            name='adress',
            field=models.CharField(default='Grorudveien 112', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meet',
            name='city',
            field=models.CharField(default='Oslo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meet',
            name='country',
            field=models.CharField(blank=True, default='Norge', max_length=100),
        ),
        migrations.AddField(
            model_name='meet',
            name='post_code',
            field=models.CharField(default='1053', max_length=7),
            preserve_default=False,
        ),
    ]
