# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-12 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='faefa', unique=True),
            preserve_default=False,
        ),
    ]
