# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-17 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_uservote'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drive_train',
            field=models.CharField(choices=[('4WD', 'Firehjulsdrift'), ('FWD', 'Forhjulsdrift'), ('RWD', 'Bakhjulsdrift')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='hp',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='car',
            name='liter',
            field=models.DecimalField(decimal_places=1, default=11, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='nm',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('V12', 'V12'), ('V10', 'V10'), ('V8', 'V8'), ('V6', 'V6'), ('R5', 'R5'), ('R4', 'R4'), ('R3', 'R3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
