# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-19 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20181217_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='first_parallax_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/mobile/parallax_1'),
        ),
        migrations.AddField(
            model_name='blog',
            name='intro_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/mobile/intro_image'),
        ),
        migrations.AddField(
            model_name='blog',
            name='paragraph_two_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/mobile/paragraph_3'),
        ),
        migrations.AddField(
            model_name='blog',
            name='second_parallax_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/mobile/parallax_2'),
        ),
        migrations.AddField(
            model_name='blog',
            name='top_image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/mobile/top_image'),
        ),
    ]
