# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-29 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20181219_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Petrol', 'Bensin'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Elektrisk')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('V12', 'V12'), ('V10', 'V10'), ('V8', 'V8'), ('V6', 'V6'), ('R6', 'R6'), ('R5', 'R5'), ('R4', 'R4'), ('R3', 'R3')], max_length=50),
        ),
    ]
