# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-14 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20181229_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='compare_image_one',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/compare'),
        ),
        migrations.AddField(
            model_name='blog',
            name='compare_image_two',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/compare'),
        ),
        migrations.AddField(
            model_name='blog',
            name='has_compare_image',
            field=models.BooleanField(default=False),
        ),
    ]
