# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-22 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20190115_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Bensin', 'Bensin'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Elektrisk', 'Elektrisk')], max_length=20, null=True),
        ),
    ]
