# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-27 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190122_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gif',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/gif'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/intro_image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='paragraph_two_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/paragraph_3'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='second_parallax',
            field=models.ImageField(blank=True, null=True, upload_to='blogs/parallax_2'),
        ),
    ]
