# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-06 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20190127_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='has_youtube_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
