# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20190206_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='has_youtube_link',
            field=models.BooleanField(default=True),
        ),
    ]
