# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-06 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20190206_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='intro_paragraph',
            field=models.CharField(max_length=1000),
        ),
    ]
