# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-19 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180823_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
