# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20180919_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
